package com.wxn.reader.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * Verifies that every app color scheme satisfies WCAG AA contrast on its X / onX colour pairs,
 * and that the warm themes' surface elevation tiers are monotonic.
 *
 * Why Robolectric: Compose's [Color] is backed by `android.graphics.Color`, which is stubbed out
 * in a plain JVM unit test. Robolectric provides the Android runtime so [Color] (and therefore
 * MaterialKolor's seed-based generation) works on the JVM without a device.
 *
 * The seed-based schemes are generated by calling the real [LightColorScheme]/[DarkColorScheme]
 * values (which delegate to MaterialKolor), not by hard-coding expected hex values — this guards
 * against the "test passes but production fails" float-rounding trap.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])  // Robolectric 4.14.1 最高支持 SDK 34；compileSdk=36 需显式锁定（同 bookread 既有做法）
class ColorSchemeContrastTest {

    private val schemes = ColorSchemeOption.entries.filter { it != ColorSchemeOption.DYNAMIC }

    private val lightSchemes = schemes.map { it.name to it.lightScheme!! }

    private val darkSchemes = schemes.map { it.name to it.darkScheme!! }

    /** WCAG AA: ≥4.5 for normal text. */
    private val MIN_CONTRAST_NORMAL = 4.5f

    @Test
    fun `every light scheme primary-onPrimary meets WCAG AA`() {
        lightSchemes.forEach { (name, scheme) ->
            val ratio = contrastRatio(scheme.primary, scheme.onPrimary)
            assertTrue("Light $name: primary/onPrimary = $ratio (need >= 4.5)", ratio >= MIN_CONTRAST_NORMAL)
        }
    }

    @Test
    fun `every dark scheme primary-onPrimary meets WCAG AA`() {
        darkSchemes.forEach { (name, scheme) ->
            val ratio = contrastRatio(scheme.primary, scheme.onPrimary)
            assertTrue("Dark $name: primary/onPrimary = $ratio (need >= 4.5)", ratio >= MIN_CONTRAST_NORMAL)
        }
    }

    @Test
    fun `every scheme surface-onSurface meets WCAG AA`() {
        (lightSchemes + darkSchemes).forEach { (name, scheme) ->
            val ratio = contrastRatio(scheme.surface, scheme.onSurface)
            assertTrue("$name: surface/onSurface = $ratio (need >= 4.5)", ratio >= MIN_CONTRAST_NORMAL)
        }
    }

    @Test
    fun `every scheme background-onBackground meets WCAG AA`() {
        (lightSchemes + darkSchemes).forEach { (name, scheme) ->
            val ratio = contrastRatio(scheme.background, scheme.onBackground)
            assertTrue("$name: background/onBackground = $ratio (need >= 4.5)", ratio >= MIN_CONTRAST_NORMAL)
        }
    }

    @Test
    fun `warm light schemes have monotonic surface elevation tiers`() {
        val warmLight = listOf(
            "Sepia" to LightSepiaScheme,
            "Parchment" to LightParchmentScheme,
            "Grey" to LightGreyScheme,
        )
        warmLight.forEach { (name, scheme) ->
            // M3 light: higher elevation = darker. So Lowest is brightest, Highest is darkest.
            assertMonotonic(name, surfaceTiers(scheme), ascending = false)
        }
    }

    @Test
    fun `warm dark schemes have monotonic surface elevation tiers`() {
        val warmDark = listOf(
            "Sepia" to DarkSepiaScheme,
            "Parchment" to DarkParchmentScheme,
            "Grey" to DarkGreyScheme,
        )
        warmDark.forEach { (name, scheme) ->
            // M3 dark: higher elevation = lighter. So Lowest is darkest, Highest is brightest.
            assertMonotonic(name, surfaceTiers(scheme), ascending = true)
        }
    }

    @Test
    fun `ColorSchemeOption has all 12 expected entries with neutral persistedKeys`() {
        val expected = setOf(
            "dynamic", "default", "grey", "sepia", "parchment", "yellow",
            "teal", "blue", "pink", "purple", "red", "green",
        )
        val actual = ColorSchemeOption.entries.map { it.persistedKey }.toSet()
        assertTrue("ColorSchemeOption missing: ${expected - actual}", actual.containsAll(expected))
    }

    // region — helpers

    /** Returns the 7 surface tiers ordered Lowest → Low → Container → High → Highest, plus Dim/Bright. */
    private fun surfaceTiers(s: ColorScheme): List<Color> = listOf(
        s.surfaceContainerLowest,
        s.surfaceContainerLow,
        s.surfaceContainer,
        s.surfaceContainerHigh,
        s.surfaceContainerHighest,
    )

    private fun assertMonotonic(name: String, tiers: List<Color>, ascending: Boolean) {
        for (i in 0 until tiers.size - 1) {
            val a = luminance(tiers[i])
            val b = luminance(tiers[i + 1])
            val ok = if (ascending) a <= b + EPSILON else a >= b - EPSILON
            assertTrue(
                "$name surface tiers not monotonic at index $i: L($a) vs L($b)",
                ok,
            )
        }
    }

    private fun contrastRatio(fg: Color, bg: Color): Float {
        val l1 = luminance(fg)
        val l2 = luminance(bg)
        val lighter = maxOf(l1, l2)
        val darker = minOf(l1, l2)
        return ((lighter + 0.05f) / (darker + 0.05f))
    }

    private fun luminance(color: Color): Float {
        val r = channelLinear(color.red)
        val g = channelLinear(color.green)
        val b = channelLinear(color.blue)
        return 0.2126f * r + 0.7152f * g + 0.0722f * b
    }

    private fun channelLinear(c: Float): Float {
        val d = c.toDouble()
        val linear = if (d <= 0.03928) d / 12.92 else Math.pow((d + 0.055) / 1.055, 2.4)
        return linear.toFloat()
    }

    private companion object {
        const val EPSILON = 0.005f
    }
    // endregion
}
